// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATfOyz1wPAJWiEaaJa8lZwZmwqcPNbd1U',
    appId: '1:806979149019:web:35f3a00ef1c2f8de36c0fe',
    messagingSenderId: '806979149019',
    projectId: 'fireflyer-7d599',
    authDomain: 'fireflyer-7d599.firebaseapp.com',
    storageBucket: 'fireflyer-7d599.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAij98xqFKTujNS5fN5mXVkfp_wuWRst9c',
    appId: '1:806979149019:android:2967580e2434147036c0fe',
    messagingSenderId: '806979149019',
    projectId: 'fireflyer-7d599',
    storageBucket: 'fireflyer-7d599.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdWEQAKkCvP2dAnkyqZWHZJB5LFaYVFo',
    appId: '1:806979149019:ios:9a484629a217ec8c36c0fe',
    messagingSenderId: '806979149019',
    projectId: 'fireflyer-7d599',
    storageBucket: 'fireflyer-7d599.appspot.com',
    iosClientId: '806979149019-51k67j94u53kue87gtlccnecvej58p45.apps.googleusercontent.com',
    iosBundleId: 'com.example.FireFlyer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdWEQAKkCvP2dAnkyqZWHZJB5LFaYVFo',
    appId: '1:806979149019:ios:c254ab6e608f532136c0fe',
    messagingSenderId: '806979149019',
    projectId: 'fireflyer-7d599',
    storageBucket: 'fireflyer-7d599.appspot.com',
    iosClientId: '806979149019-9g1mf91re9dg8eq2860bmqqppje099o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
